# Generated by Django 3.1.4 on 2020-12-12 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20201212_0512'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Program',
        ),
    ]
